### ISSUE TITLE
Table that shows which instructions are supported in which devices

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-pdk-documentation#1]
Even for the 14-bit instruction set, some such as the xor io or mul, a are not supported in all devices. So it would be good to have a table that shows instructions supported vs. device.

**Comment by spth** [comment]
I could to do this myself. Can I get commit rights?

Philipp

**Comment by spth** [comment]
See https://github.com/free-pdk/fppa-pdk-documentation/pull/9 for this information.

Philipp

**Comment by freepdk** [comment]
merged your pull request
