### ISSUE TITLE
How to update the wiki?

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-pdk-documentation#13]
How does this wiki work?
I made changes in the repository (fixed a typo, added a device) recently. What do I have to do to make this change show up in the wiki? Is there some automatic synchronization at all? Are the files that I changed in the repository just redundant duplicates of the real wiki elsewhere?

**Comment by Rakete1111** [comment]
The files here are not synchronized with the website (which the wiki links to): https://github.com/free-pdk/free-pdk.github.io

It would be great if they were.

**Comment by freepdk** [comment]
Unfortunately there is no automatic way to do it. Github support for WIKI is very limited and can not even do tables...

Manual way: copy/paste the content of the mediawiki file to a mediawiki and show preview. Then show site source and cut the inner part of the content and paste to the static html page for github.io

**Comment by FrankBuss** [comment]
Why not storing all pages directly as wiki pages at https://github.com/free-pdk/fppa-pdk-documentation/wiki ? No need to copy it redundantly.

**Comment by freepdk** [comment]
Like I said before,

github support for WIKI is VERY LIMITED. Tables are not fully working. Try it yourself.

**Comment by FrankBuss** [comment]
What about https://readthedocs.org ? I didn't try it, but other projects uses it. Will be automatically updated when something is pushed to github.

**Comment by cpldcpu** [comment]
Closing this issue, since the Wiki will no longer be needed.

https://free-pdk.github.io/
