### ISSUE TITLE
stt16 and ldt16 need to be swapped

### ISSUE THREAD

**Issue by Rakete1111** [free-pdk/fppa-pdk-documentation#14]
The documentation is wrong for those two.

> stt16  - M ← Timer16 (last bit of M set to 0, M must be word aligned)
> ldt16 - Timer16 ← M (last bit of M set to 1, M must be word aligned)

stt16 stores the word to memory, while ldt16 saves the value of the timer to the word in memory. Not sure if the last bit part of the description is correct or not. Can someone check please?

**Comment by freepdk** [comment]
fixed
