### ISSUE TITLE
Migrate partnumber.wikitext to free-pdk.github.io website (?)

### ISSUE THREAD

**Issue by cmfcmf** [free-pdk/fppa-pdk-documentation#17]
IMHO we should migrate the content of the partnumber.wikitext file to the free-pdk.github.io website.

**Comment by cpldcpu** [comment]
I also just wanted to propose that.

https://github.com/free-pdk/fppa-pdk-documentation/blob/master/partnumber.wikitext

should be easily possible to convert this to markdown. @spth what do you think?

**Comment by freepdk** [comment]
I tried to use markdown to make this... but (github) markdown does not support tables with variable columns, ... .

Feel free to convert this to any other format, as long as the result on free-pdk.github.io  looks at least as beautiful as it does now.

**Comment by cmfcmf** [comment]
Oh, we're not trying to convert the instruction set tables, just the partnumber.wikitext file which has no tables.

**Comment by freepdk** [comment]
EDIT...

just found that there is a new file called "partnumber.wikitext".

I was thinking of partnumber as a placeholder for = 13/14/15/16bit instruction .wikitext.

My bad, sorry.

**Comment by cmfcmf** [comment]
> My bad, sorry.

No worries!
