### ISSUE TITLE
Document 15-bit (or 13-bit) instruction set

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-pdk-documentation#4]
I have been in contact with Padauk. They stated that they have 3 instruction sets (14 bit, 15 bit, 16 bit). So there is a 15-bit instruction set to be documented, too.

Philipp

**Comment by spth** [comment]
On the other hand, the post http://www.eevblog.com/forum/blog/eevblog-1144-padauk-programmer-reverse-engineering/msg1976312/#msg1976312 seems to indicate that the instruction sets are 13 bit, 14 bit and 16 bit. In that case, consider this a request for the 13-bit instruction set.

Philipp

**Comment by freepdk** [comment]
first document is created

https://free-pdk.github.io/PADAUK_FPPA_13_bit_instruction_set.html

**Comment by spth** [comment]
Turns out hte 15-bit instruction set indeed exists (beside the 13-, 14- and 16-bit ones): https://www.eevblog.com/forum/blog/eevblog-1144-padauk-programmer-reverse-engineering/msg2009849/#msg2009849

So it needs to be documented.

Philipp
