### ISSUE TITLE
Document ldtabh, ldtabl in the 16-bit instruction set

### ISSUE THREAD

**Issue by spth** [free-pdk/fppa-pdk-documentation#8]
Some 16-bit devices have documented ldtabh, ldtabl instructions. These should be in the list in the wiki, too.

Philipp

**Comment by freepdk** [comment]
ldtabl and ldtabh are in the 16 bit instruction set already (right after IDXM)???

**Comment by spth** [comment]
I don't know why I missed them. Sorry for the noise.

Philipp
